name: Pull Request Checks

on:
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed

jobs:
  check-code-owner-approvals:
    uses: jgarciaga/shared-ci-steps/.github/workflows/enforce-codeowner-approvals.yml@master
    secrets:
      token: ${{ secrets.REUSABLE_WORKFLOW_TOKEN }}
    with:
      files_with_enforced_approvals: "Test.md,"