name: Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  pull_request_review:
    types: [submitted]

jobs:
  check-code-owner-approvals:
    uses: jgarciaga/shared-ci-steps/.github/workflows/enforce-codeowner-approvals.yml@feature/TEST-0011-Patch-owner_name
    with:
      files_with_enforced_approvals: "Test.md,"