name: Pull Request Checks

on:
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed

jobs:
  check-code-owner-approvals:
    uses: jgarciaga/shared-ci-steps/.github/workflows/enforce-codeowner-approvals.yml@v1.3.3
    with:
      files_with_enforced_approvals: "Test.md,"